export const ActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_LOADING: "SET_LOADING",
  DELETE_PRODUCT: "DELETE_PRODUCT",
};
